-- Solo crea la base y el usuario
CREATE DATABASE sistema_tickets_db;
CREATE USER proyecto2025 WITH PASSWORD 'proyecto2025';
GRANT ALL PRIVILEGES ON DATABASE sistema_tickets_db TO proyecto2025;
-- Permisos finales
GRANT USAGE, CREATE ON SCHEMA public TO proyecto2025;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO proyecto2025;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO proyecto2025;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO proyecto2025;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO proyecto2025;